<?php
$regionName = $this->region->getName();
$createEventId = $this->setNumber;
?>

<div class="row">
    <div id="map" class="map"></div>
</div>

<div id="dialog">
    <form action="/whathood-search">
	<input type="text" name="" placeholder="enter an address"/>
	<div>-- OR --</div>
	<div><button id="close_button" onclick="return false">Close to Explore Map</button>
    </form>  
</div>

<script>
    $('document').ready( function() {
        
        map = new RegionMap('map');
        map.addStreetLayer();

        map.addGeoJson('/whathood/neighborhood-polygon/show-region?region_name=<?=$regionName?>&create_event_id=<?=$createEventId?>&format=json', 
            function() { 
                map.addContentiousPoints( <?=$createEventId?> ); 
            }
        );

    	$( "#dialog" ).dialog();
	$("#close_button").click( function() {
	    $("#dialog").close();
	});
    });
</script>
