<?php
$regionName = $this->region->getName();
$createEventId = $this->setNumber;
?>

<div class="row">
    <div id="map" class="map"></div>
</div>

<page-info
  id="page-info"
  data-create-event-id="<?=$createEventId?>"
  data-region-name="<?=$regionName?>"
>
</page-info>

<div id="landing_dialog">
    <form id="landing_dialog_form" action="/whathood-search">
	    <input type="text" name="search_address" id="search_address" placeholder="enter an address"/>
	    <button id="landing_close_button">Close to Explore Map</button>
    </form>
</div>
