<?php
$regionName = $this->region->getName();
$createEventId = $this->setNumber;
?>

<div class="row">
    <div id="map" class="map"></div>
</div>

<page-info
  id="page-info"
  data-create-event-id="<?=$createEventId?>"
  data-region-name="<?=$regionName?>"
>
</page-info>

<!-- <div id="address-modal" class="visibility: none"> -->

<div id="address-modal" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-front ui-dialog-buttons" tabindex="-1" role="dialog" aria-describedby="address-modal" aria-labelledby="ui-id-1">
  <form>
    <input type="text" name="address" placeholder=" enter address" class="enter-address" id='enter-address'>
    <button class="btn-submit btn btn-default" id="btn-submit" type="button">Submit</button>
  </form>

  <p class='clear'>
    <span>- OR -</span>

    <button class="btn btn-default" id="current-location-btn" type="button">Current Location</button>
  </p>
</div>

<script>
$('document').ready( function() {
    Whathood.region_show();
});
</script>
