<?php
$regions = $this->regions;
$neighborhoods = $this->neighborhoods;
$queryString = $this->queryString;

?>
<div class="search_results morepadding">
    <h4>Search Results for <span class="query"><?=$queryString?></span></h4>
    
    <h5>Neighborhood Matches</h5>
    <?php if( count( $neighborhoods ) == 0 ) : ?>
        <div>No Neighborhood Matches</div>
    <?php else : ?>
        <?php foreach( $neighborhoods as $neighborhood ) :?>
        <div class="neighborhood"><a href="<?=$this->url('neighborhood', 
                    array(
                        'region_name' => $neighborhood->getRegion()->getName(), 
                        'neighborhood_name' => $neighborhood->getName() 
                    ))?>">
                <?=$neighborhood->getRegion()->getName()?> \ <?=$neighborhood->getName();?>
            </a>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>