<?php
//$this->showAddressSearchInLayout($bool = true);

// load the shit for google
$this->headScript()->appendFile("http://www.google.com/jsapi?key=AIzaSyA5m1Nc8ws2BbmPRwKu5gFradvD_hgq6G0");
?>

<div class="row centertext brand-header">
    
    <h1 class='centertext'>What Hood Is This?</h1>
    <h4 class='subtitle'>Where do you think you live?</h4>
    
</div>
<div class="row" style='padding-bottom: 25px;'>

    <div class="col-md-6 summary">
        <h2>About the project</h2>
        <p>
            WhatHood aims to settle the neighborhood debate forever.  By 
            letting users draw their own border that WhatHood mashes together 
            to create heatmaps.  Check out our <a href='http://blog.whathood.in'>
            blog for notes on the importance of a name in an area's location.</a>
        </p>
    </div>
    
    <div class="col-md-6">
        <h2>Search an address</h2>
        <?=$this->partial('application/partial-address-search-form.phtml');?>
    </div>
        <hr/>
</div>

<div class='row'>
    
    <div class='col-md-4 tri-content'>
        <h3>The hottest neighborhoods have the most fought over borders</h3>
        <div class="tri-content-content">
            <p>Fishtown is one of the hottest neighborhoods in the country, 
                but it's borders are disputed.  Checkout WhatHood's opinion.<br/>
                <br/>
                The darker the heatmap, the more that location's identity is Fishtown.
            </p>
            <img src="/images/fishtown-for-index.png" alt="Fishtown Heatmap" style="width: 100%"/>
        </div>
        <div class="tri-content-footer">
            <a href="/Philadelphia/Fishtown">
                See Fishtown
            </a>
        </div>
    </div>
    
    
    <div class='col-md-4 tri-content'>
        <h3>Recent Blog Posts</h3>
        <div id="blog-content" class="tri-content-content">Loading...</div>
        <div class="tri-content-footer">
            <a href="http://blog.whathood.in">View More</a>
        </div>
        
        
    </div>
    
    
    <div class='col-md-4 tri-content'>
        <h3>Contribute to more accurate neighborhood borders!</h3>
        <p class="tri-content-content">
            Browse the neighborhoods.  If you think you see a neighborhood 
            missing or an inaccurate border, draw it yourself.
        </p>
        <div  class="tri-content-footer">
            <a href='/n/add'>
                Add a neighborhood
            </a>
        </div>
    </div>
    
</div>



<div class="row">
        <div class='morepadding' style='text-align: left'>Browse cities</div>
        
        <?php foreach( $this->regionNames as $name ) : ?>
            <div class='row-fluid'>
                <div class='region-button btn-small span4 offset4' style='text-align: center'>
                    <a id='region-links' href="/<?php echo $name; ?>">
                        <?php echo $name; ?>
                    </a>
                </div>
            </div>
            <?php endforeach; ?>
</div>

<script type="text/javascript">
    /*
    *  How to load a feed via the Feeds API.
    */
    
    google.load("feeds", "1");
    
    // Our callback function, for when a feed is loaded.
    function feedLoaded(result) {
      if (!result.error) {
        // Grab the container we will put the results into
        var container = document.getElementById("blog-content");
        container.innerHTML = '';
    
        // Loop through the feeds, putting the titles onto the page.
        // Check out the result object for a list of properties returned in each entry.
        // http://code.google.com/apis/ajaxfeeds/documentation/reference.html#JSON
        for (var i = 0; i < result.feed.entries.length; i++) {
          var entry = result.feed.entries[i];
          var div = document.createElement("div");
          div.innerHTML = '<b><a href="'+entry.link+'">'+entry.title+'</a></b><p>' + entry.contentSnippet + '</p>';
          container.appendChild(div);
        }
      }
    }
    
    function OnLoad() {
      // Create a feed instance that will grab Digg's feed.
      var feed = new google.feeds.Feed("http://blog.whathood.in/feed");
    
      // Calling load sends the request off.  It requires a callback function.
      feed.load(feedLoaded);
    }
    
    google.setOnLoadCallback(OnLoad);
    </script>