<?php
$geoJson = \Zend\Json\Json::encode( $this->featureCollection->toGeoJsonArray() );
$regionName = $this->region->getName();
?>
<?php echo $this->mybreadcrumbs( array( 'regionName'=> $regionName ) ) ?>

<div class="row-fluid">
    <div class='centertext'>Click anywhere inside <?=$regionName?>'s borders and get the neighborhood for that location</div>
    <div id="map" class="mapheight"></div>
    
    
</div>

<script>

    $('document').ready( function() {
        
        map = new WhathoodMap({
            cssId: 'map', 
            placeCenterMarker: false,
            geoJsonSrc: '/r/border?region_name=<?=$regionName?>&format=json',
            whathoodOnClick: true
        });
    });
</script>