#!/bin/sh

sudo docker run \
    -v /home/vagrant/src/whathood/app/module/Whathood:/data \
    -v /home/vagrant/src/whathood/docs/phpdoc:/output \
    whathood/phpdoc run --visibility=public -d /data  -t /output 

sudo docker stop docs
sudo docker start docs
return 1
