#!/bin/bash

# pass in the path of the test starting from the module Whathood directory, so "test/" should start the path.
# gives the benefit of having autocomplete
# or pass nothing for all tests

test_path=`echo $@ | sed 's/^test\///g'`
sudo docker exec -it wh-nginx /bin/sh -c "cd /var/www/whathood/app/module/Whathood/test && phpunit --bootstrap Bootstrap.php -c phpunit.xml $test_path"
