#!/bin/bash

while true; do
  sudo docker exec -it wh-nginx /bin/sh -c 'cd /var/www/whathood/app; php public/index.php queue doctrine message_queue --start'
  echo `date` "message_queue worker just ended" >> /var/log/whathood/wh-worker.log
done
