<?php 
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true) );

$neighborhood = $form->get('user');

$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
    <?php echo $this->formRow($neighborhood->get('id'))?>
    <?php echo $this->formRow($neighborhood->get('userName'))?>
    <?php echo $this->formRow($form->get('submit'))?>
    <?php echo $this->form()->closeTag() ?>
</div>