<?php

$geoJson = \Zend\Json\Json::encode( $this->featureCollection->toArray() );
$regionName = $this->regionName;
$neighborhoodName = $this->neighborhoodName;
?>

<h3><?=$regionName?> <?=$neighborhoodName?> bounds</h3>
<div id="map" class="automargin mapheight" style="height: 400px;"></div>

<script>

    var geoJson = <?=$geoJson?>;

    $('document').ready( function() {
        new WhathoodMap({
            cssId: 'map',
            geoJson: geoJson,
            whathoodOnClick: true,
        });
    } );
    
</script>