<div class="row">
    <div class="col-md-8 summary">
        <h2>About the project</h2>
        <p>
            WhatHood aims to settle the neighborhood boundary debate forever.  The days
            of a small group deciding over what is where are over.  This the 21st
            century!  Google doesn't know where neighborhoods are.  Neither does
            Foursquare, or Twitter, or Yelp, or Zillow, or Trulia.  But they're guessing.
            And it matters, it matters a whole lot.  Do you want to
            sell your house?  Whether you live in Fishtown, or across the street could cost you thousands.
        </p>
    </div>
</div>

<div class='row'>

    <div class='col-md-6 tri-content'>
        <h3>The hottest neighborhoods have the most fought oer borders</h3>
        <div class="tri-content-content">
            <p>Fishtown is one of the hottest neighborhoods in the country,
                but it's borders are disputed.  Checkout WhatHood's opinion.<br/>
                <br/>
                The darker the heatmap, the more that location's identity is Fishtown.
            </p>
            <img src="/images/fishtown-for-index.png" alt="Fishtown Heatmap" style="width: 100%"/>
        </div>
        <div class="tri-content-footer">
            <a href="/Philadelphia/Fishtown">
                See Fishtown
            </a>
        </div>
    </div>

    <div class='col-md-6 tri-content'>
        <h3>Contribute to more accurate neighborhood borders!</h3>
        <p class="tri-content-content">
            Browse the neighborhoods.  If you think you see a neighborhood
            missing or an inaccurate border, draw it yourself.
        </p>
        <div  class="tri-content-footer">
        <a href='<?php echo $this->url("user_neighborhood/add") ?>'>
                Add a neighborhood
            </a>
        </div>
    </div>

</div>
