<?=$this->mybreadcrumbs()?>

<?php foreach( $this->neighborhoods as $neighborhood ) : ?>
    <div class="neighborhood-list">
        <?php //echo $n->getUser()->getName(); ?>
        <a href="<?=$this->url('neighborhood_id', array(
                'neighborhood_id'   => $neighborhood->getId()
                ));?>">
            <?php echo $neighborhood->getId()
                    ." "
                    .$neighborhood->getNeighborhood()->getRegion()->getName()
                    ." \ "
                    .$neighborhood->getNeighborhood()->getName(); ?>
        </a>
    </div>
<?php endforeach; ?>
