<div class="display" cellspacing="0" width="100%">
<table id="up_dataTable" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>id</th>
                <th>Created</th>
                <th>Neighborhood Name</th>
                <th>Region</th>
            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th>id</th>
                <th>Created</th>
                <th>Neighborhood Name</th>
                <th>Region</th>
            </tr>
        </tfoot>
    </table>
</div>
<script>
  $(document).ready( function() {
    window.Whathood.neighborhood.list()
  });
</script>
