<?php
$neighborhood = $this->neighborhood;
$region_name = $neighborhood->getRegion()->getName();
$np = $this->neighborhood_polygon;

$this->headTitle()->prepend($this->neighborhood->getName() . ' / ' . $this->neighborhood->getRegion()->getName() );
?>

<div id="map" ng-controller="WhathoodNeighborhoodController" class="map"
  data-neighborhood-name="<?=$neighborhood->getName()?>"
  data-region-name="<?= $region_name ?>"
  data-neighborhood-id="<?=$neighborhood->getId()?>"
  data-neighborhood-polygon-created-at="<?php if ($np) echo date_format($np->getCreatedAt(),'Y-m-d H:i:s')?>"
  data-neighborhood-polygon-id="<?php if ($np) echo $np->getId() ?>"
  data-num-user-polygons="<?= $this->user_polygon_count ?>"
  data-np-grid-resolution="<?php if ($np) echo $np->getGridResolution() ?>"
  data-np-target-precision="<?php if ($np) echo $np->getTargetPrecision()?>">
</div>

