<?php
$neighborhood = $this->neighborhood;
$region_name = $neighborhood->getRegion()->getName();
$np = $this->neighborhood_polygon;

$this->headTitle()->prepend($this->neighborhood->getName() . ' / ' . $this->neighborhood->getRegion()->getName() );
?>

<h3>
  <a href="/<?=$region_name?>"><?=$region_name?></a> \ <?=$neighborhood->getName()?>
</h3>
<p>Based one<a href="<?php echo $this->url('user_neighborhood/page_neighborhood', array( 'region' => $this->neighborhood->getRegion()->getName(), 'neighborhood' => $this->neighborhood->getName(), 'page' => 0 )) ?>">
        <?=$this->user_polygon_count?> user drawn borders
    </a>
</p>
<div id="map" data-neighborhood-id="<?=$neighborhood->getId()?>" data-neighborhood-polygon-created-at="<?=date_format($np->getCreatedAt(),'Y-m-d H:i:s')?>" data-neighborhood-polygon-id="<?= $this->neighborhood_polygon->getId() ?>" data-np-grid-resolution="<?= $np->getGridResolution() ?>" data-np-target-precision="<?=$np->getTargetPrecision()?>" class="automargin mapheight" style="height: 400px;"></div>

<script>
    $('document').ready( function() {
        window.Whathood.neighborhood_polygon_show();
    });
</script>
