<?php
/*
 * application/heat-map/show.phtml
 */
$heatMapJsData      = $this->heatMap->getHeatMapJsData();
$heatMapMax         = $this->heatMap->getMax();
$heatMapId          = $this->heatMap->getId();

$regionName         = $this->regionName;
$neighborhoodName   = $this->neighborhoodName;

$this->headTitle()->prepend( $neighborhoodName . ", " . $regionName . " Neighborhood Boundaries" );
$this->headMeta()->setProperty('description', "The neighborhood boundaries for $neighborhoodName, $regionName");
?>
<?php
echo $this->mybreadcrumbs( array(
    'regionName'        => $regionName,
    'neighborhoodName'  => $neighborhoodName
));?>

<div class="morepadding">
    <p>This heatmap was built by using these neighborhood borders:</p>
    <?php foreach( $this->heatMap->getNeighborhoodPolygons() as $np ) :?>
        <span style="padding-right: 20px"><a href="/n/id/<?=$np->getId()?>"><?=$np->getWhathoodUser()->getUserName()?></a></span>
    <?php endforeach; ?>
</div>
<div class="row-fluid">
    <?=$this->partial('application/partial_whathood_click_notification.phtml');?>
    <div id="map" class=""></div>
</div>

<?php
echo $this->heatMapDisqus( $this->regionName,$this->neighborhoodName );
?>
<script>
    $('document').ready( function() {
        
        var data = <?=$heatMapJsData?>;
        var heatMapMax = <?=$heatMapMax?>;
        
        map = new WhathoodMap({
            cssId: 'map',
            regionName: 'Philadelphia',
            heatMapData: data,
            heatMapMax: heatMapMax,
            whathoodOnClick: true,
            zoom: 14,
            leaflet: {
                maxZoom: 14,
                minZoom: 14
            }
        });
    });
</script>