<?php

$this->headTitle()->prepend("Browse user polygons at point y ".$this->y." x ".$this->x);

if (!$this->paginator->count()) :
    throw new \Exception("no polygons found for this center");

else :
    echo $this->paginationControl(
        $this->paginator,
        'Sliding',
        'whathood/user-polygon/user_polygon_pagination_control.phtml',
        array(
            'paginator' => $this->paginator,
            'route' => 'user-polygon-page-list',
        )
    );
?>

<?php    foreach ($this->paginator as $user_polygon) : ?>

        <form class="form-horizontal">
            <div class="form-group">
                <label for "input_id" class="col-sm-3 control-label">Id</label>
                <p id="input_id" class="col-sm-9 form-control-static"><?=$user_polygon->getId()?></p>
            </div>
            <div class="form-group">
                <label for="input_name" class="col-sm-3 control-label">Neighborhood Name</label>
                <div class="col-sm-9">
                    <p id="input_name" class="form-control-static"><?=$user_polygon->getNeighborhood()->getName()?></p>
                </div>

            </div>
            <div>
                <div class="col-sm-9">
                  <label for "input_ip_address" class="col-sm-3 control-label">IP Address</label>
                    <p id="input_ip_address" class="form-control-static"><?=$user_polygon->getWhathoodUser()->getIpAddress()?></p>
                </div>
            </div>
                <input type='hidden' name="user_polygon_id" data-user_polygon_id="<?=$user_polygon->getId()?>"
                    data-x="<?=$this->x?>"
                    data-y="<?=$this->y?>"
                    data-neighborhood_name="<?=$user_polygon->getNeighborhood()->getName()?>"
                >
        </form>

        <div class="row">
            <div id="map" class="map user_polygon_page_map"></div>
        </div>

    <?php endforeach; ?>

<?php endif; ?>


<script>
    $('document').ready( function() {
        Whathood.user_polygon_page_id();
    });
</script>
