<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'whathood/user-polygon/user_polygon_pagination_control.phtml',
                                    array(
                                        'paginator' => $this->paginator,
                                        'route' => 'user-polygon-page-list',
                                    )
                );
?>

<?php foreach( $this->paginator as $item ) : ?>
    <input data-user_polygon_id="<?=$user_polygon->getId()?>">
<?php endforeach; ?>
