<?php
$regions = $this->regions;
$neighborhoods = $this->neighborhoods;
$queryString = $this->queryString;
?>
<div class="search_results morepadding">
    <h4>Search Results for <span class="query"><?=$queryString?></span></h4>

    <h5>Region Matches</h5>
    <?php if( count( $regions ) == 0 ) : ?>
        <div>No Region Matches</div>
    <?php else : ?>
        <?php foreach( $regions as $region ) :?>
        <div class="region"><a href="<?=$this->url('region',
                    array(
                        'region' => $region->getName()
                    ))?>">
                <?=$region->getName()?>
            </a>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <h5>Neighborhood Matches</h5>
    <?php if( count( $neighborhoods ) == 0 ) : ?>
        <div>No Neighborhood Matches</div>
    <?php else : ?>
        <?php foreach( $neighborhoods as $neighborhood ) :?>
        <div class="neighborhood"><a href="<?=$this->url('neighborhood',
                    array(
                        'region' => $neighborhood->getRegion()->getName(),
                        'neighborhood' => $neighborhood->getName()
                    ))?>">
                <?=$neighborhood->getRegion()->getName()?> \ <?=$neighborhood->getName();?>
            </a>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
