<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
        
        /**
         * Title
        *************************************************/
        
        $this->headTitle()->setSeparator(' / ');
        if( !$this->isProductionEnvironment() ) 
            $this->headTitle()->prepend("[DEVELOPMENT]"); 
        
        echo $this->headTitle("What Hood Is This?"); ?>

        <?php 
        /**
         * ViewPort Meta
         */
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0') . "\n"; ?>
        
<script type="text/javascript">
    if (window.location.hash == '#_=_'){
        window.location.hash = '';
    }
</script>

    <!-- 
        jQuery
    ==========================================================-->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>    
    
        
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
    
    <!--
        Twitter Bootstrap
    ===========================================================-->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script>

    <!--
        Leaflet.js
    ==========================================================-->
    <!--<script src="/js/leaflet-draw/libs/leaflet-src.js"></script>-->
    <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet-src.js"></script>
    <link rel="stylesheet" href="/js/leaflet-draw/libs/leaflet.css" />
	<!--[if lte IE 8]><link rel="stylesheet" href="/js/leaflet-draw/libs/leaflet.ie.css" /><![endif]-->
	<link rel="stylesheet" href="/js/leaflet-draw/css/leaflet.draw.css" />
	<!--[if lte IE 8]><link rel="stylesheet" href="/js/leaflet-draw/css/leaflet.draw.ie.css" /><![endif]-->
    
    <!--
        Leaflet.draw
    ==========================================================-->
	<script src="/js/leaflet-draw/js/leaflet.draw.js"></script>

    <!--
        Spin.js
    ==========================================================-->
	<script src="/js/spin.min.js"></script>
    
    <!--
        Leaflet.spin
    ========================================================-->
	<script src="/js/leaflet.spin.js"></script>

    
    <!--
        JQueryUI
    =====================================================-->
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    
    <!--
        Google Maps
    ======================================================-->
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7AjCGLXahpd8NO8DZ0kHBwWSR_r58kMI&sensor=false">
    </script>
    
    <!--
        HeatMap.js
    ======================================================-->
    <script type="text/javascript" src="/js/heatmapjs/src/QuadTree.js"></script>
    <script type="text/javascript" src="/js/heatmapjs/src/heatmap.js"></script>
    <script type="text/javascript" src="/js/heatmapjs/src/heatmap-leaflet-jsmiley-edit.js"></script>
    
    <!--
        Whathood
    ====================================================-->
    <script type="text/javascript" src="/js/whathood.js"></script>
    <?php echo $this->headLink()
                    ->prependStylesheet( '/css/style.css' )?>

    <!-- any other javascript
    ===================================================-->
    <?php echo $this->headScript(); ?>
         
    <!-- any other styles 
    =================================================-->
    <?php echo $this->headStyle(); ?>

    <!-- choose a font
    =================================================-->
    <link href='http://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Stoke' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    
    </head>
    <body>
        
    <!-- Navbar
    ================================================== -->
    <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">What Hood Is This?</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a class="active" href="/">Home</a></li>
          
          <?php echo $this->partial('application/partial_login-menu-item.phtml'); ?>
        </ul>
        <form class="navbar-form navbar-right" role="search"  action="<?=$this->url( 'search' )?>">
          <div class="form-group">
            <input type="text" name="q" class="search-query" placeholder="enter neighborhood or city">
          </div>
        </form>
      </div><!-- /.navbar-collapse -->
    </nav>

    
    <?php if( true && !$this->isProductionEnvironment() ) :?>
        <div style='height: 30px; position:absolute; top: 0; left: 0; z-index:1031;background:red; color: white; text-align: center; vertical-align: middle'>
            <p style='vertical-align: middle'>DEVELOPMENT</p>
        </div>
    <?php endif; ?>
    
        <!-- Body
        ================================================== -->
        <div class="container main-container">
            <?php echo $this->content; ?>
        </div><!-- main-container -->   
            
            
            <!-- Footer
            ============================================== -->
            <footer class="muted centertext row-fluid">
                <div class='row-fluid'>
                    <p class="centertext morepadding">
                        <small>
                            A project by
                            Justin Crone
                            and
                            <a href="http://twitter.com/jimRsmiley" target="_blank">Jim Smiley</a>
                        </small>
                    </p>
                </div>

                <div class="span4">
                    
                </div>
                
                <div class="span3">
                    
                </div>
                
                <div class="span4" style='text-align: left'>
                    <h5>Contact</h5>
                    <ul>
                        <li>email: <a href='mailto:info@whathood.in'>info@whathood.in</a></li>
                        <li>twitter: <a href='http://twitter.com/whathood'>@whathood</a></li>
                    </ul>
                   
                </div>
                
                
            </footer>
            
        <?php echo $this->inlineScript() ?>

        <?php echo $this->partial('application/partial-google-analytics.phtml');?>
            
    </body>
</html>
