
    <!--
        jQuery
    ==========================================================-->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>


    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    <!--
        Twitter Bootstrap 3.3.2
    ===========================================================-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!--
        Leaflet.js
    ==========================================================-->
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

    <!--
        Leaflet.draw
    ==========================================================-->
    <!--[if lte IE 8]><link rel="stylesheet" href="/js/leaflet-draw/libs/leaflet.ie.css" /><![endif]-->
       <link rel="stylesheet" href="/js/leaflet-draw/css/leaflet.draw.css" />
       <!--[if lte IE 8]><link rel="stylesheet" href="/js/leaflet-draw/css/leaflet.draw.ie.css" /><![endif]-->

    <link rel="stylesheet" href="/js/Leaflet.markercluster/dist/MarkerCluster.css">
    <link rel="stylesheet" href="/js/Leaflet.markercluster/dist/MarkerCluster.Default.css">

    <!--
        JQueryUI
    =====================================================-->
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

    <!--
        Google Maps
    ======================================================-->
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7AjCGLXahpd8NO8DZ0kHBwWSR_r58kMI&sensor=false">
    </script>

    <!--
        React
    ======================================================-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>

    <!--
        DataTables
    =======================================================-->
    <link rel="stylesheet" href="/js/lib/DataTables-1.10.8/media/css/jquery.dataTables.css">

    <!--
        Angular
    =======================================================-->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.2/angular-route.min.js"></script>

    <script type="text/javascript" src="/js/bundle.js"></script>

    <?php echo $this->headLink()
                    ->prependStylesheet( '/css/whathood-less.css' )?>

    <!-- any other javascript
    ===================================================-->
    <?php echo $this->headScript(); ?>

    <!-- any other styles
    =================================================-->
    <?php echo $this->headStyle(); ?>

    <!-- choose a font
    =================================================-->
    <link href='http://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Stoke' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
