<!DOCTYPE html>
<html ng-app="myApp" lang="en">
    <head>
        <meta charset="utf-8">
        <?php

        /**
         * Title
        *************************************************/

        $this->headTitle()->setSeparator(' / ');

        echo $this->headTitle('What hood is this - What neighborhood do you think you live in?'); ?>

        <?php
        /**
         * ViewPort Meta
         */
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0') . "\n"; ?>

        <?php echo $this->partial( 'layout/partial/rollbar.phtml' ); ?>
<script type="text/javascript">
    if (window.location.hash == '#_=_'){
        window.location.hash = '';
    }
</script>

    <?php echo $this->partial( 'layout/header-includes.phtml' ); ?>

    </head>
    <body>

      <div id="wh-config" style="display: none"
        data-wh-environment="<?= \Whathood\Util::environment() ?>">
      </div>

    <?php echo $this->partial( 'layout/navbar.phtml' ); ?>

        <!-- Body
        ================================================== -->
        <div class="container main-container">
            <?php echo $this->content; ?>
        </div><!-- main-container -->

        <?php echo $this->inlineScript() ?>

        <?php echo $this->google_analytics() ?>

    </body>
</html>
