
    <!-- Navbar
    ================================================== -->
    <nav class="navbar navbar-default" role="navigation">

    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">What 'hood is this?</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li>
            <a href="/about">About</a>
          </li>
        </ul>

        <form class="navbar-form navbar-right" role="search"  action="<?=$this->url( 'home/search' )?>">
          <div class="form-group">
            <input type="text" name="q" class="search-query" placeholder="enter neighborhood or city">
          </div>
        </form>

      </div><!-- /.navbar-collapse -->
    </nav>
