<?php if( $this->auth()->isLoggedIn() ) : 
    
    $whathoodUserId = $this->auth()->getWhathoodUser()->getId();
    $userName = $this->auth()->getWhathoodUser()->getUserName();
    $logoutUrl = $this->auth()->logoutUrl();
    ?>

    <li class="dropdown">
      <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">Welcome <?=$userName?><span class="caret" style="vertical-align: middle"></span></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <li><a tabindex="-1" href="<?=$this->url('user_by_name',array('whathood_user_name' => $userName ) )?>">My Neighborhoods</a></li>
          <li class="divider"></li>
          <li><a tabindex="-1" href="<?=$logoutUrl?>">Logout</a></li>
      </ul>
    </li>

<?php else : ?>
    
    <li class="">
        <a href="<?=$this->auth()->loginUrl()?>">Login</a>
    </li>
    
<?php endif; ?>