<form class="form-horizontal" action='/auth/login'>
<fieldset>

<!-- Form Name -->
<legend>Pick A Username</legend>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="userName">User Name</label>
  <div class="controls">
    <input id="userName" name="userName" type="text" placeholder="enter desired username" class="input-xlarge" required="">
  </div>
</div>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="textinput">User Name Available: </label>
  <div class="controls">
    <span id="message" class="input-xlarge"></span>
  </div>
</div>

<!-- Button -->
<div class="control-group">
  <label class="control-label" for="submit"></label>
  <div class="controls">
    <button id="submit" name="submit" class="btn btn-primary">Submit</button>
  </div>
</div>

</fieldset>
</form>

<script type="text/javascript">
 
$(document).ready(function(){
   $("#userName").keyup(username_check);
});
                
                
username_check = function(){

    console.log('at least we are checking');
    
    var username=$("#userName").val();

    if(username === "" || username.length < 4)
    {
    }
    else {
        $("#message").html("<img src='ajax-loader.gif' /> checking...");

        $.ajax({
           type:"post",
           url:"/user/check-user-name-availability",
           data: {userName:username},
           success:function(data){
               console.log( data );
               if(data.result == 'available'){
                   $("#message").html("<img src='tick.png' /> Username available");
                   $('#submit').show();
               }
               else{
                   $("#message").html("<img src='cross.png' /> Username already taken");
                   $('#submit').hide();
               }
           },
           error: function (xhr, ajaxOptions, thrownError) {
                    console.log(xhr);
                    console.log(xhr.status);
                    console.log( 'response text: ' + xhr.responseText );
                    console.log(thrownError);
                }
        });
    }
};

</script>