#!/bin/bash


DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APP_DIR="/var/www/whathood"
SRC_DIR=$DIR/..

echo ""
echo "Building Whathood App"
echo ""
sudo mkdir -p $APP_DIR

cd $SRC_DIR/app
echo "*     installing composer"
curl -sS https://getcomposer.org/installer | php > /dev/null
echo "*     installing vendor libraries"
php composer.phar install > /dev/null
echo "*     configuring Whathood Zend"

echo "*     copying whathood zend files"
cp -r $SRC_DIR/app $APP_DIR

echo "*     copying over ZcfUser config files"
cp $SRC_DIR/dev-bin/provision/ZfcUserDoctrineORM.Entity.User.dcm.xml $APP_DIR/app/vendor/zf-commons/zfc-user-doctrine-orm/config/xml/zfcuserdoctrineorm -f
cp $SRC_DIR/dev-bin/provision/ZfcUser.Entity.User.dcm.xml $APP_DIR/app/vendor/zf-commons/zfc-user-doctrine-orm/config/xml/zfcuser/ -f

echo "*     building Whathood's coffeescript(to do)"
echo "*     building grunt"
# DO NOT SUDO GRUNT
cd $APP_DIR
npm config set loglevel warn
npm install --silent grunt --save-dev > /dev/null
npm install --silent grunt-contrib-watch --save-dev > /dev/null
npm install --silent grunt-contrib-coffee --save-dev > /dev/null

echo "*     building coffeescript into whathood-compiled.js"
grunt coffee > /dev/null
