#!/usr/bin/env ruby


backup_dir=File.new(Dir.new(".").path).expand+"/data/whathood_db"

BACKUP_FILE="whathood_bak.sql"

puts "dumping database to #{BACKUP_FILE}"
cmd="pg_dump --no-owner whathood > #{backup_dir}/#{BACKUP_FILE}"

puts cmd

system cmd

puts backup_dir
Dir.chdir backup_dir

time = Time.new
`git add #{BACKUP_FILE}`
`git commit -m "re-exported whathood sql created at #{time}"`
`git push`
