#!/bin/bash

DIR=$HOME/jim_whathood_bak/whathood_sql
BACKUP_FILE=$DIR/whathood_bak.sql

mkdir -p $DIR

echo "dumping database to $BACKUP_FILR"
pg_dump \
    --no-owner \
    --exclude-table whathood_user \
    --exclude-table facebook_user \
    jim_whathood \
    > $BACKUP_FILE

#pg_dump --table whathood_user \
#    --table facebook_user \
#    jim_whathood \
#    > $HOME/jim_whathood_bak.sql


cd $DIR

git add . -A
git commit -m 're-exported whathood sql'
git push
