#!/bin/bash

ln -s app/module/Whathood/src/Whathood/ W
ln -s app/module/Whathood/config/module.config.php module.config.php
ln -s app/config/autoload/user_security.global.php user_security.global.php
ln -s app/module/Whathood/view view
ln -s app/public/js/whathood/whathood.js whathood.js
