#!/usr/bin/env ruby

require 'optparse'
require_relative '../libs/ruby/Whathood/Util.rb'

OptionParser.new do |opts|
  opts.on('--db-name [DB_NAME]') do |value|
    $DB_NAME = value
  end
end.parse!

DB_NAME = $DB_NAME || ( ENV.has_key?('PGDATABASE') ? ENV['PGDATABASE'] : 'whathood' )
DB_HOST = ( ENV.has_key?('PGHOST') ? ENV['PGHOST'] : 'wh-postgis' )
DB_USER = 'docker'

ROOT_DIR=File.dirname(__FILE__)+"/.."

script_dir = "#{ROOT_DIR}/app/scripts/sql"

def run_sql_script(file)
    Whathood::Util.run_cmd("psql -h #{DB_HOST} -U #{DB_USER} --tuples-only --quiet -f #{file} #{DB_NAME}")
end

def import_files(dir_str)
    files = Dir.glob(dir_str)
    files = files.sort
    files.each do |f|
        puts "processing #{DB_NAME}: #{f}"
        run_sql_script(f)
    end
end

puts "loading whathood.function.*.sql INTO #{DB_NAME}"
import_files("#{script_dir}/whathood.function.*.sql")
puts "loading whathood.view.*.sql"
import_files("#{script_dir}/whathood.view.*.sql")

puts "done"

