#!/bin/bash

ln -s app/module/Whathood/src/Whathood/ W
ln -s app/module/Whathood/config/module.config.php module.config.php
ln -s app/config/autoload/user_security.global.php user_secuirity.global.php
ln -s app/module/Whathood/view view
